export { default as Header } from './header/Header'
export { default as Hero } from './hero/Hero'
export { default as About } from './about/About'
export { default as CTA } from './cta/CTA'
export { default as Benefits } from './benefits/Benefits'